### ISSUE TITLE
One policy for all?

### ISSUE THREAD

**Issue by rwaldron** [WICG/Realms-Initialization-Control#37]
Let's say I have a large platform application that allows different orgs to deploy their own custom components to be run only for that org's account on my platform, and I'm going to run all of that code in a child realm. If my pages load with: 

```
Content-Security-Policy: "realm-init: /scripts/on-new-same-origin-realm.js"
```

Does that mean that all iframes created will all be subject to whatever is written in `scripts/on-new-same-origin-realm.js`? I can't see a way for my application to decide which realms should have this realm-init policy applied.

**Comment by weizman** [comment]
The RIC proposal focuses on giving you generic control over all same origin realms within your app so you could tame power they might have against you, which isn't possible in web's current design, mostly because of the realms you **do not** create within your app.

For your use case, where you want to be the first to run code in a realm you **do** create, you have plenty of existing tools, such as loading a remote HTML with the first script tag being your script, or for local iframes just attach them to DOM and run your code within them atomically.

**Comment by weizman** [comment]
If an app chose to make use of the RIC directive, then it made a choice to run that script in all realms by design.
Therefore, it made a choice to apply its restrictions upon your iframe too.

While they're expected to be cautious with such power and run safe code that won't harm yours, they're entitled of doing so, which is the power balance this proposal attempts to restore.

This is of course solvable, since they write the code, they can at any point update it to exclude your iframe:

```javascript
// Content-Security-Policy: "realm-init: /scripts/on-new-same-origin-realm.js"
if (shouldIframeBeExcluded(window)) stop-running;
```

But this proposal shouldn't focus on implementing a builtin mechanizm for telling whether a realm should be excluded or not **securely**, as it would introduce quit an overhead in complexity for a not well justified use case.

**Comment by rwaldron** [comment]
Ok, I think that amount of control is suitable. Thanks!
