### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by weizman** [WICG/Realms-Initialization-Control#4]
Use cases of the [RIC proposal](https://github.com/weizman/Realms-Initialization-Control) are needed.

If you find this proposal useful, its probably because you have a use case for it.

Sharing it with us would help a lot in showing the community this is an important issue to fix.

You can either share here or open a PR.

**Comment by eligrey** [comment]
[airgap.js](https://docs.transcend.io/docs/consent-management/capabilities) would adopt this API for efficient privacy protections if shipped in browsers. We currently hook realm creation (requires airgap.js 9.0+) but are limited by platform capabilities for some realm creation sources.

**Comment by nicjansma** [comment]
Akamai has a few products that could use something like this:

* We have a real user monitoring (RUM) product that wraps a lot of top-level APIs for performance and error telemetry.  For example:
    * `XMLHttpRequest` and `fetch` to monitor network performance
    * `addEventListener` to get better call stacks for errors
* We have bot management and security products that wrap APIs for protection and monitoring

Our existing patching techniques generally just [swap our own function](https://github.com/akamai/boomerang/blob/master/boomerang.js#L2529-L2546) in for the native one, and squirrel away the original incase we need to "un-patch".

We've seen cases in the past where this patching can conflict with other third-parties who use slightly-different techniques or have different expectations.  Problems can arise when the loading order between the third-parties is not controlled, and one library may not work well when loaded first/last.

Having a better-defined way of being able to control patching would probably help with stability and security-related concerns like above.  We would definitely consider something like this to harden our existing "patching" techniques.

**Comment by yoavweiss** [comment]
Shopify sandboxes various scripts in different ways. One of them ([the lax sandbox](https://shopify.dev/docs/apps/build/marketing-analytics/pixels#lax-sandbox-custom-web-pixel)) is using a same-origin sandboxed iframe. Custom overriding of native functions further restricts the capabilities that code running in these iframes has access to. Being able to perform those overrides as the (guaranteed) first script that runs in these iframes would help us ensure that malicious code doesn't attempt to escape those restrictions.

**Comment by kzar** [comment]
I could imagine browser extensions like Adblock Plus and DuckDuckGo Privacy Essentials using this if it became available. I wrote up more of an explanation on [this related proposal](https://github.com/tc39/proposal-shadowrealm/issues/406), but the short version is that to stop adverts and fingerprinting such extensions often need to wrap certain APIs, to restrict how the website uses them. We attempt this already, for example see [this old Adblock Plus code](https://github.com/adblockplus/adblockpluschrome/blob/master/inject.preload.js), but there are seemingly unending tricks websites use to circumvent us.

Having it managed via a CSP header sounds good, since extensions can add those and they are additive (so we won't undo the website's CSP header if there was one present). But my question would be what if the website already set the new `realm-init` directive? Ideally for our use case, in that situation our `realm-init` directive would "win", but I wonder about the details there. If that wasn't the case, we'd be stuck parsing and editing the CSP headers ourselves which would be error prone and I worry would lead to making the CSP of some websites weaker by accident.

**Comment by weizman** [comment]
Hi @kzar, thanks for participating,

To be honest, I don't think RIC is the right place for such use case, because RIC's purpose is to help web apps regain control over their own (same origin) realms, without taking extensions into account. That's why we decided to introduce this via CSP - it's the security policy API the browser provides for websites, not for extensions.

AFAIA, CSP directives that can be added on aren't a thing, so we'll definitely won't focus our energy towards challenging that in this proposal. I know that extensions that need to modify the CSP headers of websites when introduced by a website, usually do so by parsing and editing its content before serving it on to the user (as you mention). If this isn't good enough (as you say), I'm afraid that sounds like a new issue (unrelated to RIC).

Sorry if I mislead you earlier [here](https://github.com/tc39/proposal-shadowrealm/issues/406#issuecomment-2174207586), I think I misunderstood the situation there 🙏

**Comment by kzar** [comment]
Browser extensions can add response headers, and in fact Adblock Plus and the other ad blockers already do support adding CSP headers [using the $csp filter option](https://blog.adblockplus.org/development-builds/added-support-for-the-csp-filter-option). I don't have the spec link to hand, but when multiple CSP response headers are active, each one can make the policy more restrictive but never less restrictive. I think you will need to consider what happens when there are two or more CSP headers with a `realm-init` directive active at the same time therefore.

**Comment by weizman** [comment]
You learn something new every day

https://github.com/WICG/Realms-Initialization-Control/issues/6

Thank you @kzar
